[profile.default]
src = 'contracts'
out = 'foundry/out'
libs = ['node_modules', 'foundry/lib']
test = 'test/foundry'
cache_path = 'foundry/forge_cache'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config